language: python

python:
  - 2.7

services: postgresql

env:
  - DJANGO=1.7.4 DB=postgresql

before_script:
 - psql -c 'create database educoding_test;' -U postgres

before_install:
  - export DJANGO_SETTINGS_MODULE=educoding.settings
  - pip install codecov

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet


script:
  - coverage run manage.py test

after_success:
  - codecov