language: python

python:
  - 2.7

services: sqlite

env:
  - DJANGO=1.7.4 DB=sqlite

before_install:
  - export DJANGO_SETTINGS_MODULE=codeaton.settings
  - pip install codecov

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet


script:
  - python manage.py test

after_success:
  - codecov