# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-04-07 05:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Exercise', '0003_exercise_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='author',
        ),
        migrations.AddField(
            model_name='exercise',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
