# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-04-07 05:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Exercise', '0004_auto_20190407_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='author',
        ),
        migrations.AddField(
            model_name='exercise',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
