# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0005_auto_20150324_0005'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='class_to_add',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
